[package]
name = "rinha-2026"
version = "0.1.0"
edition = "2024"

[dependencies]
aligned-vec = "0.6.4"
bytes = "1.11.1"
flate2 = { version = "1.1.9", default-features = false, features = ["rust_backend"] }
http = "1.4.0"
mimalloc = { version = "0.1.50", default-features = false }
monoio = { version = "0.2.4", features = ["sync"] }
monoio-http = "0.3.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
sonic-rs = "0.5.8"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bin]]
name = "build_index"
path = "src/bin/build_index.rs"

[[bench]]
name = "score"
harness = false
