services:
  api1:
    build: .
    platform: linux/amd64
    environment:
      - LISTEN_UDS=/sockets/api1.sock
    volumes:
      - sockets:/sockets
    networks:
      - backend
    security_opt:
      - seccomp=unconfined
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 165MB
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    build: .
    platform: linux/amd64
    environment:
      - LISTEN_UDS=/sockets/api2.sock
    volumes:
      - sockets:/sockets
    networks:
      - backend
    security_opt:
      - seccomp=unconfined
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 165MB
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  lb:
    image: haproxy:lts-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 20MB
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  sockets:

networks:
  backend:
    driver: bridge
