services:
  api1:
    build: .
    environment:
      - LISTEN_UDS=/sockets/api1.sock
    volumes:
      - sockets:/sockets
    networks:
      - backend
    security_opt:
      - seccomp=unconfined
    cpu_period: "10000"
    cpu_quota: "4000"
    deploy:
      resources:
        limits:
          memory: 165MB
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    build: .
    environment:
      - LISTEN_UDS=/sockets/api2.sock
    volumes:
      - sockets:/sockets
    networks:
      - backend
    security_opt:
      - seccomp=unconfined
    cpu_period: "10000"
    cpu_quota: "4000"
    deploy:
      resources:
        limits:
          memory: 165MB
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  lb:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend
    cpu_period: "10000"
    cpu_quota: "2000"
    deploy:
      resources:
        limits:
          memory: 20MB
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 4096

volumes:
  sockets:

networks:
  backend:
    driver: bridge
